CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Properties" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PropertyType" character varying(100) NOT NULL,
    "BedroomCount" integer NOT NULL,
    "Location" character varying(300) NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    "BathroomCount" integer NOT NULL,
    "Area" numeric(10,2) NOT NULL,
    "ParkingAvailable" boolean NOT NULL,
    "Description" character varying(1000) NOT NULL,
    "HasGarden" boolean NOT NULL,
    "HasPool" boolean NOT NULL,
    "Status" text NOT NULL,
    CONSTRAINT "PK_Properties" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240420154516_InitialCreate', '8.0.4');

COMMIT;

